"""
Django settings for proj project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
import logging

from typing import List

import toml

class _Config:
    def __init__(self, path):
        with open(path) as f:
            self.toml = toml.load(f)
        return

    def __getattr__(self, name):
        return self.toml["trigger"][name]


_logger = logging.getLogger(__name__)

_c = _Config(os.environ.get("TOML_SETTINGS_TOML", "settings.toml"))

is_prod = _c.ENV == "prod"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = not is_prod

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

SECRET_KEY = _c.SECRET_KEY

ALLOWED_HOSTS = [
    _c.ALLOWED_HOST
]

# Named URL Pattern
LOGIN_URL = "login"

SESSION_COOKIE_NAME = "trigger_sessionid"
SESSION_COOKIE_SECURE = is_prod


# Application definition

INSTALLED_APPS = [
    # Do not forget to add app or django cannot find templates!
    "trigger.apps.TriggerConfig",
    "proj.manageproj.apps.AppConfig",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "proj.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ]
        },
    }
]

WSGI_APPLICATION = "proj.wsgi.application"


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    # TODO: Use dj_database_url
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": _c.SQLITE3,
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_L10N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = "/static/"


# trigger specific

TRIGGER_PUSHBULLET_TOKEN = _c.PUSHBULLET_TOKEN

globals()["HANIHO"] = 1
